spring:
  application:
    name: trace
  datasource:
    url: jdbc:postgresql://localhost:5432/rms_db?currentSchema=rms_db_dbo
    username: souki
    password: soukipass
    driver-class-name: org.postgresql.Driver
