spring.application.name=java-file-io
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/{database}
#spring.datasource.username={username}
#spring.datasource.password={password}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
