spring.application.name=java-file-io
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/{database}
#spring.datasource.username={username}
#spring.datasource.password={password}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.connection-timeout=60000
server.tomcat.connection-timeout=60000
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=120s

logging.level.org.springframework.=TRACE
