server:
  port: 8080

logging:
  file:
    name: logs/lms-client-application.log
  level:
    root: TRACE
    org:
      springframework: TRACE

spring:
  application:
    name: lms-client-application
  security:
    oauth2:
      client:
        registration:
          lms-client-oidc:
            provider: spring
            client-id: client-id-lms-client-oidc
            client-secret: secretABC
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: lms-client-oidc
          lms-client-authorization-code:
            provider: spring
            client-id: client-id-lms-client-authorization-code
            client-secret: secretXYZ
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: lms.read
            client-name: lms-client-authorization-code
#          [registrationId]:
#            provider: [providerId]
#            client-id: client-id-lms-client-authorization-code
#            client-secret: secret
#            client-authentication-method: 
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/authorized"
#            scope: lms.read
#            client-name: lms-client-authorization-code
        provider:
#          [providerId]:
#            authorization-uri: http://{base_url}/oauth2/v1/authorize
#            token-uri: http://{base_url}/oauth2/v1/token
#            jwk-set-uri: http://{base_url}/oauth2/v1/keys
#            issuer-uri: 
#            user-info-uri: http://{base_url}/oauth2/v1/userinfo
#            user-info-authentication-method:
#            user-name-attribute:
          spring:
            issuer-uri: http://auth-server:9000

