server:
  port: 9000

logging:
  file:
    name: logs/lms-authorization-server.log
  level:
    root: TRACE
    org:
      springframework: TRACE

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
        client:
          lms-client:
            registration:
              client-id: lms-client
              client-secret: "{noop}secret"
              client-name: LMS Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/lms-client-oidc
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - profile
                - lms.read
                - lms.write
                