name: Java CI with Maven

on:
  push:
    branches: feature/java-file-io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd java-file-io && mvn -B package --file pom.xml
